---
project: multi_task_learning
experiment_desc: mtl1
phase: train
warmup_num: 0
model:
    g_name: resnet
    blocks: 9
    d_name: n_layers
    d_layers: 3
    content_loss: perceptual
    disc_loss: wgan-gp
    learn_residual: True
    backbone: resnet34
    pretrained: False
    norm_layer: instance
    dropout: True  
num_epochs: 100
num_workers: 2
datasets:
  - type: unaligned
    batch_size: 8
    dataroot_train: /home/ml/DeblurGAN/GOPRO_Large
    dataroot_val: /home/ml/DeblurGAN/GOPRO_Large
    fineSize: 256
  - type: haze
    batch_size: 8
    dataroot_train: /home/ml/DeblurGAN/GOPRO_Large
    dataroot_val: /home/ml/DeblurGAN/GOPRO_Large
    fineSize: 256
image_size: [256, 256]
D_update_ratio: 5
loss:
    cont: 100
optimizer:
    name: adam
    lr_G: 0.0001
    lr_D: 0.0002
scheduler:
    name: linear
    start_epoch: 50
    min_lr: 0.0000001

